# Generated by Django 4.2.7 on 2024-01-11 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stamp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=20)),
                ('val', models.IntegerField()),
            ],
        ),
    ]
