# Generated by Django 4.2.7 on 2024-01-11 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stamp', '0002_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='test',
            new_name='Brou',
        ),
    ]
