# Generated by Django 5.0.4 on 2024-04-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stamp', '0003_rename_test_brou'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tel',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
