# Generated by Django 5.0.4 on 2024-04-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stamp', '0004_alter_customuser_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patternstamp',
            name='adresse_Entreprise',
        ),
        migrations.RemoveField(
            model_name='patternstamp',
            name='ape_Entreprise',
        ),
        migrations.RemoveField(
            model_name='patternstamp',
            name='email_Entreprise',
        ),
        migrations.RemoveField(
            model_name='patternstamp',
            name='format',
        ),
        migrations.RemoveField(
            model_name='patternstamp',
            name='format_dateur',
        ),
        migrations.RemoveField(
            model_name='patternstamp',
            name='logo_Entreprise',
        ),
        migrations.RemoveField(
            model_name='patternstamp',
            name='maxlines',
        ),
        migrations.RemoveField(
            model_name='patternstamp',
            name='nom_Entreprise',
        ),
        migrations.RemoveField(
            model_name='patternstamp',
            name='nui_Entreprise',
        ),
        migrations.RemoveField(
            model_name='patternstamp',
            name='taille_ecritue',
        ),
        migrations.RemoveField(
            model_name='patternstamp',
            name='tel_Entreprise',
        ),
        migrations.RemoveField(
            model_name='patternstamp',
            name='type_Entreprise',
        ),
        migrations.AddField(
            model_name='patternstamp',
            name='image_example',
            field=models.ImageField(blank=True, upload_to='MEDIA/image_example/PatternStamp'),
        ),
    ]
