# Generated by Django 5.0.4 on 2024-04-21 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stamp', '0005_remove_patternstamp_adresse_entreprise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patternstamp',
            name='image_example',
            field=models.ImageField(upload_to='MEDIA/image_example/PatternStamp'),
        ),
    ]
