# Generated by Django 5.0.4 on 2024-04-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stamp', '0007_alter_patternstamp_forme'),
    ]

    operations = [
        migrations.AddField(
            model_name='monture',
            name='dimensions',
            field=models.CharField(blank=True, choices=[('DIM_6X8', '6cm x 8 cm')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='monture',
            name='forme',
            field=models.CharField(blank=True, choices=[('ROND', 'Rond'), ('CARRE', 'Carré')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='monture',
            name='image_example',
            field=models.ImageField(blank=True, null=True, upload_to='MEDIA/image_example/Monture'),
        ),
        migrations.AlterField(
            model_name='monture',
            name='type',
            field=models.CharField(blank=True, choices=[('BOIS', 'BOIS'), ('PLASTIQUE_MECANIQUE', 'En plastique avec mequanisme de Rabattement'), ('PLASTIQUE_INSOLE', 'En plastique  avec gaumme insoléz')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patternstamp',
            name='forme',
            field=models.CharField(blank=True, choices=[('ROND', 'Rond'), ('CARRE', 'Carré')], max_length=255, null=True),
        ),
    ]
